# Generated by Django 4.2.1 on 2023-12-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_applications_rename_progress_create_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='id',
        ),
        migrations.AddField(
            model_name='applications',
            name='q_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applications',
            name='q_exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applications',
            name='q_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tender',
            name='t_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
