# Generated by Django 4.2.1 on 2023-12-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_tender_id_applications_q_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_profile',
            name='C_name',
        ),
    ]
