# Generated by Django 4.2.1 on 2023-12-10 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_company_profile_c_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='company_name',
        ),
    ]
