# Generated by Django 4.2.1 on 2023-12-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_applications_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='c_email',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
