# Generated by Django 4.2.1 on 2023-12-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_applications_c_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='c_email',
            field=models.CharField(max_length=50),
        ),
    ]
